config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'videos#index'

  resources :videos
  resources :music
  resources :games
  resources :books
  resources :captions, param: :video_id, only: :show
  get 'search/:word', as: :search, action: :search, controller: :dictionaries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
  def self.search(word) # rubocop:disable Style/DisableCopsWithinSourceCodeDirective, Metrics/MethodLength
    query = <<-SQL.squish
      SELECT
        JSON_EXTRACT(
          LOWER( dictionary -> '$.*' ),
          JSON_UNQUOTE(
            JSON_SEARCH(
              LOWER( dictionary -> '$**.word' ),
              'one',
              LOWER( ? )
            ))) result
      FROM
        dictionaries
      WHERE name = LOWER( ? );
    SQL

    ActiveRecord::Base.connection.execute sanitize_sql_array [query, word, "#{word.first}.json"]
  end
end

app/models/video.rb
class Video < ApplicationRecord
  has_one_attached :caption

  validates :video_id, length: { is: 11 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/captions_controller.rb
class CaptionsController < ApplicationController
  before_action :set_video, :download, only: %i[download show]

  def show
    @caption = ReadCaption.new(@video.caption).parse
    render partial: 'show', locals: { caption: @caption }
  end

  private

  def set_video
    @video = Video.find_or_initialize_by video_id: video_id
  end

  def download
    return if @video.caption.attached?

    CaptionDownloaderJob.perform_now @video
  end

  def video_id
    params[:video_id]
  end
end

app/controllers/concerns/read_caption.rb
class ReadCaption
  def initialize(file)
    @caption = file.open { |f| f.each_line.map(&:chomp).split { |line| line == '' } }
  end

  def parse
    @caption =
      @caption.map.with_index do |line, idx|
        next if idx.zero? || line.blank?

        times = line[0].split ' --> '
        text = line - [line[0]]
        { start: times[0], end: times[1], text: text.join("\n").remove('&nbsp;') }
      end

    @caption.compact
  end
end

app/controllers/concerns/youtube.rb
require 'google/apis/youtube_v3'

Google::Apis.logger.level = Logger::DEBUG

class Youtube
  def initialize
    @service = Google::Apis::YoutubeV3::YouTubeService.new
    @service.key = 'AIzaSyCDjuS0D88blEsG-hH_BfYum5sdbc5qxuE'
  end

  def list_searches(
    part: 'snippet', channel_id: nil, max_results: 10,
    fields: 'items(id(videoId), snippet(channelTitle, thumbnails(medium), title))'
  )
    @service.list_searches part, channel_id: channel_id, max_results: max_results, fields: fields
  rescue Google::Apis::ServerError, Google::Apis::ClientError, Google::Apis::AuthorizationError => e
    raise e
  end

  # def list_captions(part: 'id', video_id: nil, fields: 'items(id)')
  #   @service.list_captions(part, video_id, fields: fields)
  # rescue Google::Apis::ServerError, Google::Apis::ClientError, Google::Apis::AuthorizationError => e
  #   raise(e)
  # end

  # def download_caption(id: nil, tfmt: 'vtt', fields: nil)
  #   @service.download_caption(id, tfmt: tfmt, fields: fields)
  # rescue Google::Apis::ServerError, Google::Apis::ClientError, Google::Apis::AuthorizationError => e
  #   raise(e)
  # end
end

# def initialize
#   @service = Google::Apis::YoutubeV3::YouTubeService.new
#   @service.authorization = Google::Auth::ServiceAccountCredentials.make_creds(
#     json_key_io: File.open('./config/google-cred.json'),
#     scope: [Google::Apis::YoutubeV3::AUTH_YOUTUBE, Google::Apis::YoutubeV3::AUTH_YOUTUBE_FORCE_SSL]
#   )
#   @service.authorization.fetch_access_token!
# end

# require 'googleauth'
# require 'googleauth/web_user_authorizer'
# require 'googleauth/stores/file_token_store'

# client_id = Google::Auth::ClientId.from_file(CLIENT_SECRETS_PATH)
# scope = Google::Apis::YoutubeV3::AUTH_YOUTUBE_READONLY
# token_store = Google::Auth::Stores::FileTokenStore.new(file: CREDENTIALS_PATH)
# authorizer = Google::Auth::WebUserAuthorizer.new(client_id, scope, token_store, '/oauth2callback')

# get('/authorize') do
#   # NOTE: Assumes the user is already authenticated to the app
#   user_id = request.session['user_id']
#   credentials = authorizer.get_credentials(user_id, request)
#   redirect authorizer.get_authorization_url(login_hint: user_id, request: request) if credentials.nil?
#   # Credentials are valid, can call APIs
#   # ...
# end

# get('/oauth2callback') do
#   target_url = Google::Auth::WebUserAuthorizer.handle_auth_callback_deferred(request)
#   redirect target_url
# end

# class Youtube
#   REDIRECT_URI = 'http://localhost:2000/'
#   APPLICATION_NAME = 'Bootstrap'
#   CLIENT_SECRETS_PATH = File.join('config', 'secrets', 'client_secret.json')
#   CREDENTIALS_PATH = File.join('config', 'credentials', 'credentials.yml')
#   SCOPE = Google::Apis::YoutubeV3::AUTH_YOUTUBE_READONLY

#   def initialize
#     client_id = Google::Auth::ClientId.from_file(CLIENT_SECRETS_PATH)
#     token_store = Google::Auth::Stores::FileTokenStore.new(file: CREDENTIALS_PATH)
#     authorizer = Google::Auth::UserAuthorizer.new(client_id, SCOPE, token_store)
#     user_id = ENV['USER']
#     credentials = authorizer.get_credentials(user_id)
#     if credentials.nil?
#       url = authorizer.get_authorization_url(base_url: REDIRECT_URI)
#       puts('Open the following URL in the browser and enter the ' + 'resulting code after authorization')
#       puts(url)
#       code = gets
#       credentials = authorizer.get_and_store_credentials_from_code(
#         user_id: user_id, code: code, base_url: REDIRECT_URI
#       )
#     end
#     puts(credentials.nil?)
#     # credentials
#   end

#   private_constant :REDIRECT_URI
#   private_constant :APPLICATION_NAME
#   private_constant :CLIENT_SECRETS_PATH
#   private_constant :CREDENTIALS_PATH
#   private_constant :SCOPE
# end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  def search
    result = entries
    return head :no_content if result.blank?

    render partial: 'word', locals: { entries: result }, status: :ok
  end

  private

  def word
    params[:word]
  end

  def entries
    origin = Dictionary.where word: word
    return origin if origin.present?

    Dictionary.where word: word.singularize
  end
end

# plural = Dictionary.where word: word
# word_pluralize = word.pluralize

# [word.singularize, word_pluralize]
# pluralize_query = query.where word: word_pluralize
# query = pluralize_query if pluralize_query.present?

# def new
#   @dictionary = Dictionary.new
# end

# def create
#   dictionary = Dictionary.new name: dictionary_param.original_filename,
#                               dictionary: JSON.parse(dictionary_param.read)
#   render plain: dictionary.save
# end

# def dictionary_param
#   params.require(:dictionary).permit(:dictionary)[:dictionary]
# end

# render json: json_file[0]['meanings']

# uri = URI.parse 'https://api.dictionaryapi.dev/api/v2/entries/en/'.concat params[:word]
# res = Net::HTTP.get_response uri
# return render json: res.body, status: :ok if res.is_a? Net::HTTPSuccess

# head :service_unavailable

# include PyCall::Import
# pyfrom :PyDictionary, import: :PyDictionary
# dict = PyDictionary
# render plain: dict.meaning('love').to_json

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :video, only: :show

  def index
    file = File.read Rails.root.join('youtube.json')
    object = JSON.parse file
    @items = object['items']

    # render plain: search
  end

  def show
    head :no_content unless @video
  end

  private

  def video
    @video = Video.find_by video_id: params[:id]
  end

  def search(channel_id = 'UCHaHD477h-FeBbVh9Sh7syA')
    Youtube.new.list_searches(channel_id: channel_id).to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def image(src = 'placeholder.jpeg', options: {})
    image_tag src, options
  end

  def icon_tag(class_name, role: nil, data: {})
    content_tag :i, nil, { class: 'icon fa-solid '.concat(class_name), role: role }.merge(data)
  end
end

app/views/captions/_show.html.erb
<ul class="caption-list">
  <% caption.each do |line| %>
    <li class="caption">
      <%= icon_tag "toggle fa-2x fa-circle-play",
                   role: :button,
                   data: { "data-start": line[:start], "data-end": line[:end] } %>
      <p>
        <% line[:text].split do |word| %>
          <span class="word" role="button" tabindex="0" ><%= word %></span>
        <% end %>
      </p>
    </li>
  <% end %>
</ul>

app/views/dictionaries/_word.html.erb
<ol class="list-group">
  <% entries.each_with_index do |entry, index| %>
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <div class="fw-bold">
          <%= entry['word'] %>
          <a
            href="https://en.wiktionary.org/wiki/Wiktionary:Abbreviations_in_Webster"
            class="small text-muted"
            target="_blank"
          >
            <%= entry['wordtype'] %>
          </a>
        </div>
        <%= entry['definition'] %>
      </div>
    </li>
  <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render "layouts/customs/navbar" %>
    <div class="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/customs/_navbar.html.erb
<nav class="menu-bar">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img
        src="/bootstrap-logo.svg"
        alt="avatar"
        width="30"
        height="24"
        role="button"
      >
        <span>Bootstrap</span>
      </a>
      <form class="search">
        <%= icon_tag "fa-magnifying-glass", role: :button %>
        <div class="dropdown">
          <input
            class="dropdown-toggle"
            type="search"
            placeholder="Search"
            autocomplete="off"
          >
            <ul class="dropdown-menu">
              <li>
                <button class="dropdown-item" type="button">Action</button>
              </li>
              <li>
                <button class="dropdown-item" type="button">Another action</button>
              </li>
              <li>
                <button class="dropdown-item" type="button">
                  Something else here
                </button>
              </li>
            </ul>
          </div>
        </form>
        <div class="navbar-user">
          <a class="dropdown-toggle" data-bs-toggle="dropdown" role="button">
            <img
          class="avatar"
          src="/bootstrap-logo.svg"
          alt="avatar"
          width="30"
          height="24"
          role="button"
        >
              My name
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action dadasd</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li>
                <a class="dropdown-item" href="#">Something else</a>
              </li>
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li><a class="dropdown-item" href="#">Separated link</a></li>
            </ul>
          </div>
        </div>
      </nav>

app/views/videos/_caption.html.erb
<div class="caption-container">
  <div class="card">
    <div class="card-header">
      <%= icon_tag "btn-chevron-down",
                   role: :button,
                   data: { "data-bs-toggle": :tooltip, "data-bs-placement": :bottom, title: "Slide down" } %>
      Subtitles
      <%= icon_tag "btn-close caption-box",
                   role: :button,
                   data: { "data-bs-toggle": :tooltip, "data-bs-placement": :bottom, title: "Close" } %>
      <span
        class="form-switch"
        data-bs-toggle="tooltip"
        data-bs-placement="bottom"
        title="Auto scroll"
      >
        <input class="form-check-input" type="checkbox" id="auto-scroll" checked>
        <label class="form-check-label small" for="auto-scroll"></label>
      </span>
    </div>
    <div class="card-body">
      <%= render_async caption_path(video.video_id),
                       retry_count: 5,
                       error_message: "Couldnot fetch it, please press F5 or reload page",
                       content_for_name: :caption do %>
        <ul class="caption-list">
          <% 15.times do |time| %>
            <li class="caption">
              <div class="placeholder-glow btn ps-0 pe-2">
                <%= icon_tag "fa-circle-play fa-2x placeholder rounded-circle" %>
              </div>
              <p class="placeholder-glow w-100">
                <span class="placeholder col-12"></span>
              </p>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>
<%= content_for :caption %>

app/views/videos/_video.html.erb
<div class="video-container">
  <div class="video-player">
    <svg
      class="place-holder"
      width="100%"
      height="100%"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      preserveAspectRatio="xMidYMid slice"
      focusable="false"
    >
      <rect width="100%" height="100%"></rect>
    </svg>
    <div id="youtube" data-videoid="<%= video.video_id %>"></div>
    <div class="more-videos d-none"></div>
  </div>
  <div class="video-controller">
    <div class="card-header">
      <p class="card-text">...</p>
    </div>
    <div class="card-body">
      <div>
        <span class="btn-repeat disabled-gray disabled">
          <%= icon_tag "fa-repeat disabled-gray fa-inverse", role: :button %>
          <%= icon_tag "fa-1 fa-inverse d-none", role: :button %>
        </span>
        <span class="btn-caption-toggle disabled">
          <%= icon_tag "fa-closed-captioning disabled fa-inverse", role: :button %>
          <%= icon_tag "fa-slash d-none", role: :button %>
        </span>
      </div>
      <div>
        <%= icon_tag "btn-prev disabled-gray fa-inverse", role: :button %>
        <%= icon_tag "btn-play disabled fa-circle-play fa-inverse", role: :button %>
        <%= icon_tag "btn-next disabled-gray fa-inverse", role: :button %>
      </div>
      <div>
        <span class="btn-caption disabled">
          <%= icon_tag "fa-rectangle-list disabled fa-inverse", role: :button %>
          <%= icon_tag "fa-slash d-none", role: :button %>
        </span>
        <!-- <span class="btn-group">
          <%= icon_tag "btn-speed disabled fa-inverse",
                       role: :button,
                       data: { "data-bs-toggle": :dropdown, "data-bs-display": :static } %>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">x 0.5</a></li>
            <li><a class="dropdown-item" href="#">x 0.75</a></li>
            <li><a class="dropdown-item active" href="#">x 1.0</a></li>
            <li><a class="dropdown-item" href="#">x 1.5</a></li>
          </ul>
        </span>
        <span class="btn-group">
          <%= icon_tag "btn-more disabled fa-inverse",
                       role: :button,
                       data: { "data-bs-toggle": :dropdown, 'data-bs-display': :static } %>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Font size</a></li>
          </ul>
        </span> -->
      </div>
    </div>
  </div>
</div>

app/views/videos/_vocabulary.html.erb
<div class="vocabulary-container">
  <span class="word" tabindex="0">jojojojo</span>
</div>

app/views/videos/index.html.erb
<div class="videos-index">
  <% @items.each do |item| %>
    <% video_id = item["id"]["videoId"] %>
    <% snippet = item["snippet"] %>
    <% thumbnail = snippet["thumbnails"]["medium"] %>
    <div class="card">
      <a href="/videos/<%= video_id %>">
        <%= image_tag "placeholder.jpeg",
                      class: "card-img-top img-fluid lazy",
                      width: "100%",
                      height: thumbnail["height"],
                      alt: "thumbnail",
                      "data-src": thumbnail["url"] %>
        <div class="card-body">
          <h6 class="card-title placeholder-glow">
            <span class="placeholder col-12">
              <%= snippet["title"] %>
            </span>
          </h6>
        </div>
      </a>
    </div>
  <% end %>
</div>

app/views/videos/show.html.erb
<div class="videos-show">
  <%= render partial: "video", locals: { video: @video } %>
  <%= render partial: "caption", locals: { video: @video } %>
  <%= render partial: "vocabulary", locals: { video: @video } %>
</div>